export const LOAD_COMPANY_LIST_REQUEST = 'LOAD_COMPANY_LIST_REQUEST'
export const LOAD_COMPANY_LIST_SUCCESS = 'LOAD_COMPANY_LIST_SUCCESS'
export const LOAD_COMPANY_LIST_FAILURE = 'LOAD_COMPANY_LIST_FAILURE'

export const CHECKED_COMPANY = 'CHECKED_COMPANY'
export const UNCHECKED_COMPANY = 'UNCHECKED_COMPANY'
